### ISSUE TITLE
CentOS 8.5.2111 测试获取不到任何的流量信息

### ISSUE THREAD

**Issue by Liang2580** [rfyiamcool/go-netflow#4]
![image](https://user-images.githubusercontent.com/27684409/172591952-c5cfc811-ecf6-44f5-9036-146d2b005d39.png)

使用的为cmd/main.go

**Comment by Liang2580** [comment]
测试Ubuntu 20.04.2 也获取不到任何流量信息

**Comment by rfyiamcool** [comment]
监听的网络设备不对？
