### ISSUE TITLE
统计结果不准确

### ISSUE THREAD

**Issue by Gypsying** [rfyiamcool/go-netflow#5]
测试机上python3开了个http.server提供下载测试，这个抓包显示每秒4.6MB：
![image](https://user-images.githubusercontent.com/17995262/181177352-22aa1b7a-7a39-4ec1-8212-44fd32b7573f.png)

但是远远小于实际带宽值：
![image](https://user-images.githubusercontent.com/17995262/181177411-f7104e6c-3a01-42fb-a1a5-eecc370a8272.png)

补充：recentSeconds设置15秒，8核16G虚机，抓包统计程序占用了1.5核左右，偏高。

**Comment by rfyiamcool** [comment]
python里开了三个线程去下载？  然后用 netflow 去检测python下载程序 ？
